version: "3.8" 
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drivelink
      MYSQL_ROOT_PASSWORD: root

    container_name: mysqldb-drivelink
    ports:
      - "3306:3306"
  app:
    build:
      context: ./
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
       - ./.mysql.env
    container_name: drivelink
    tty: true
    ports:
      - "80:80"
      
    networks:
      - drivelink

networks:
  drivelink: