version: "3.8" 
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: drivelink
      MYSQL_ROOT_PASSWORD: root

    container_name: mysqldb-drivelink
    ports:
      - "3308:3306"
    networks:
      - drivelink




  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - drivelink

  app:
    build:
      context: ./
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.mysql.env
    container_name: drivelink
    tty: true
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    networks:
      - drivelink

networks:
  drivelink: